### ISSUE TITLE
Error when building burn on Windows when upgrading to tch 0.16

### ISSUE THREAD

**Issue by syl20bnr** [LaurentMazare/tch-rs#870]
We tried  to update tch to 0.16 which adds support for pytorch 2.3 in [burn](https://github.com/tracel-ai/burn) and we get a compilation error on Windows:

```
INTEL MKL ERROR: The specified module could not be found. mkl_def.1.dll.
Intel MKL FATAL ERROR: Cannot load mkl_def.1.dll.
```

Reverting to 0.15 fix this error. 

This compilation error has been reproduced on our CI and on our Windows desktop.

**Comment by LaurentMazare** [comment]
Looks like this is related to https://github.com/pytorch/pytorch/issues/124009 , there seems to be a fix in place so you may want to give a try to the nightly build until 2.3.1 is out (I think it's scheduled for the beginning of June).

**Comment by antimora** [comment]
Looks like the upstream issue is fixed. Do we need to do anything @LaurentMazare , @syl20bnr ?

**Comment by syl20bnr** [comment]
This is still a problem:

> INTEL MKL ERROR: The specified module could not be found. mkl_vml_def.1.dll.
  Intel MKL FATAL ERROR: cannot load mkl_vml_def.1.dll.
